version: '3'
services:
  web:
        image: nginx:latest
        container_name: nginx
        restart: always
        volumes:
            - ./src:/src
        links:
            - php
  php:
       build: .
       container_name: php
       ports:
            - "80:80"
       volumes:
            - ./src/:/var/www/html
