version: '3'
services:
  web:
        image: nginx
        container_name: nginx
        restart: always
        volumes:
            - ./src:/src
            - ./nginx-config/default.conf:/nginx-config/default.conf

        ports:
            - 80:80
        depends_on:
            - php
  php:
       image: php:8.0
       build: .
       container_name: php
       volumes:
            - ./src:/src
