version: '3'
services:
  nginx:
        image: nginx:alpine
        volumes:
            - ./src:/src
            - ./nginx-config/:/etc/nginx/conf.d/
        ports:
            - 80:80

        depends_on:
            - php
        
  php:
       image: php:7.3-fpm-alpine
       volumes:
            - ./src:/src
